# [ERROR] Flyte Task decorator Error
```python
Traceback (most recent call last):
  File "/usr/local/bin/pyflyte-execute", line 8, in <module>
    sys.exit(execute_task_cmd())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flytekit/bin/entrypoint.py", line 470, in execute_task_cmd
    _execute_task(
  File "/usr/local/lib/python3.8/site-packages/flytekit/exceptions/scopes.py", line 160, in system_entry_point
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flytekit/bin/entrypoint.py", line 348, in _execute_task
    _handle_annotated_task(ctx, _task_def, inputs, output_prefix)
  File "/usr/local/lib/python3.8/site-packages/flytekit/bin/entrypoint.py", line 291, in _handle_annotated_task
    _dispatch_execute(ctx, task_def, inputs, output_prefix)
  File "/usr/local/lib/python3.8/site-packages/flytekit/bin/entrypoint.py", line 80, in _dispatch_execute
    logger.debug(f"Starting _dispatch_execute for {task_def.name}")
AttributeError: 'function' object has no attribute 'name'
```
Flyte Task를 decorator로 실행하지 않고 fucntion으로 호출하면 위와 같은 오류가 발생할 수 있따.

# [ERROR] Flyte `launch plan {launch_plan_name} failed to update due to rpc error: code = NotFound desc = missing entity of type LAUNCH_PLAN with identifier project:"alert" domain:"development" name:"func_name" version:"xxxxxxxxxxxxx"`
launch plan이 포함된 파이썬 파일이 모듈화되어 있지 않아 오류가 발생하였다. __init__.py을 포함하여 제대로 모듈화하도록 한다.

# [ERROR] AttributeError: 'Promise' object has no attribute 'year'
```python
def nyears_ago(date: datetime.datetime, n: int) -> datetime.datetime:
    return datetime.datetime(date.year - n, date.month, date.day)
   
@workflow()
def workflow_at(date: datetime.datetime, freq: str):
    start = nyears_ago(date=date, n=3)
    ...
```
`workflow_at`에서 전달받은 인자를 task로 정의하지 않은 함수 `nyears_ago`에 사용하면 오류가 발생한다. @task, @workflow에서 사용하는 인자는 Flyte 데이터 타입인 Promise이다.
    
