# [ERROR] Flyte `AssertionError: Cannot pass output from task alert.util.run.flytekit.core.python_function_task.xxx.xx.. that produces no outputs to a downstream task`

기본적으로 Flyte task가 반환하는 값은 VoidPromise type으로 다른 task로 넘길 때 오류가 발생한다. task function을 정의할 때 아래처럼 return type을 명시해야 한다.
```python
import typing
from typing import Tuple
from flytekit import task


@task
def t1(a: int) -> typing.NamedTuple("OutputsBC", t1_int_output=int, c=str):
    return a + 2, "world"

@task
def t2(a: str, b: str) -> str:
    return b + a
```

```python
@workflow
def my_wf(a: int, b: str) -> Tuple[int, str]:
    x, y = t1(a=a)
    print(x,y)
    d = t2(a=y, b=b)
    return x, d
```
예시로 workflow에서 t1의 결과값 type을 출력해보면 다음과 같다. 
```console
Resolved(t1_int_output=scalar {
  primitive {
    integer: 102
  }
}
) Resolved(c=scalar {
  primitive {
    string_value: "world"
  }
}
)
```

# [ERROR] Flyte `AttributeError: 'function' object has no attribute 'python_interface'`
workflow가 아닌 function을 실행하면 발생하는 오류

# [ERROR] Flyte `flytekit.exceptions.system.FlyteSystemException: Error looking for LHS in xx.xx`
decorator에서 declarative workflow를 생성하면 오류가 발생하여 imperative workflow로 생성하여 수정하였다.


