# [ERROR] `error initializing keycloak provider: failed to perform initial login to Keycloak: error sending POST request to https://{url}/auth/realms/{my-realm}/protocol/openid-connect/token: 404 Not Found`

```
provider = keycloak.Provider("keycloak_provider", base_path="", client_id="REDACTED", client_secret="REDACTED",
url="REDACTED")
realm = keycloak.Realm("new-python-realm", realm="Pulumi", opts=pulumi.ResourceOptions(provider=provider))
```
keycloak 버전 18 이상부터 base path에 /auth가 빠졌는데 기본값으로 pulumi에서 /auth를 추가하여 keycloak 서버에 접속한다. `base_path=""`로 설정해야 한다. keycloak provider로 설정할 시 client_id, client_secret, url을 같이 추가해야 한다.

> [Pulumi Keycloak From Keycloak version 17, there are no "/auth" in the path](https://github.com/pulumi/pulumi-keycloak/issues/148)

